name: Bump-version

on:
  push:
    branches: [ beta, master ]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-key: dependencies
        node-version: '12.x'
      with:
        path: ~/.npm
        key: ${{ env.cache-key }}-${{ env.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ env.cache-key }}-${{ env.node-version }}-
          ${{ env.cache-key }}-

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Bump version
      run: |
        git config user.name GitHub Action
        git config user.email action@github.com

        if (( ${{ contains(github.ref, 'master') }} )); then
          npx standard-version
          git push --follow-tags origin master
        else
          npx standard-version --prerelease beta
          git push --follow-tags origin beta
        fi

      if: contains(github.ref, 'beta')
    - name: Publish beta version on NPM
      run: npm publish --access public --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
