name: Publish-latest

on:
  release:
    types: [ created ]
    branches: [ master ]

jobs:
  test-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com/'

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-key: dependencies
      with:
        path: ~/.npm
        key: ${{ env.cache-key }}-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ env.cache-key }}-${{ github.ref }}-
          ${{ env.cache-key }}-

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Publish on NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
