name: CI

on:
  pull_request:
    branches: [ develop, beta, master ]
    types: [ opened, synchronize, reopened ]

jobs:
  test-dev:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-key: dependencies
      with:
        path: ~/.npm
        key: ${{ env.cache-key }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ env.cache-key }}-${{ matrix.node-version }}-
          ${{ env.cache-key }}-

    - name: Install dependencies
      run: npm ci

    - name: Check commit messages
      uses: wagoid/commitlint-github-action@v2

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
